(def! new-library
      (let* ((set-name! (fn* (mname new-name) (reset! mname new-name)))
             (add-book! (fn* (mbooks book) 
                             (swap! mbooks (fn* (lst) (cons book lst)))))
             (dispatch (fn* (msg mname mbooks)
                            (cond ((= msg 'name) (deref mname))
                                  ((= msg 'books) (deref mbooks))
                                  ((= msg 'set-name!) 
                                   (fn* (name) (set-name! mname name)))
                                  ((= msg 'add-book!)
                                   (fn* (book) (add-book! mbooks book)))
                                  (true (throw (list "unknown message" msg)))))))
        (fn* (name books)
             (let* ((mname (atom name))
                    (mbooks (atom books)))
               (fn* (msg) (dispatch msg mname mbooks))))))

(def! library-name (fn* (lib) (lib 'name)))
(def! library-books (fn* (lib) (lib 'books)))
(def! library-set-name! (fn* (lib name) ((lib 'set-name!) name)))
(def! library-add-book! (fn* (lib book) ((lib 'add-book!) book)))

(def! lib (new-library 'eureka '()))
(library-add-book! lib '("Hackers" "Steven Levy"))
(library-add-book! lib '("Anathem" "Neal Stephenson"))
(library-add-book! lib '("The Gay Science" "Friedrich Nietzsche"))
